FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3

LABEL org.opencontainers.image.title="OC" \
      org.opencontainers.image.source="https://github.com/soulteary/mc"

COPY oc /usr/bin/oc
COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE
COPY NOTICE /licenses/NOTICE
COPY internal/notify/LICENSE /licenses/notify-LICENSE

RUN microdnf install ca-certificates --nodocs && microdnf clean all

ENTRYPOINT ["oc"]
